name = "Networks"
uuid = "634dcf3f-6aa7-47ba-9e85-1fb329c9ebfe"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez+git@bsc.es>"]
version = "0.3.0"

[deps]
DelegatorTraits = "d83dbd90-3e00-4b33-84f1-398adcf3b35e"

[compat]
DelegatorTraits = "0.1.2"
julia = "1.10"
